DROP SEQUENCE "~SQ_NEWS";

DROP TABLE "~NEWS";


CREATE OR REPLACE FUNCTION "~STATISTICS"()
  RETURNS refcursor AS
$BODY$
declare
	_c refcursor;
begin
	OPEN _c FOR EXECUTE
	'SELECT
		(SELECT COUNT(*) FROM "CITY") AS COUNT_CITY,
		(SELECT COUNT(*) FROM "COMPLEX") AS COUNT_COMPLEX,
		(SELECT COUNT(*) FROM "COUNTRY") AS COUNT_COUNTRY,
		(SELECT COUNT(*) FROM "EVENT") AS COUNT_EVENT,
		(SELECT COUNT(*) FROM "PERSON") AS COUNT_PERSON,
		(SELECT COUNT(*) FROM "RESULT") AS COUNT_RESULT,
		(SELECT COUNT(*) FROM "SPORT") AS COUNT_SPORT,
		(SELECT COUNT(*) FROM "TEAM") AS COUNT_TEAM';
	RETURN  _c;
end;
$BODY$
  LANGUAGE 'plpgsql' VOLATILE
  COST 100;
  
  CREATE INDEX "PR_LAST_NAME_INDEX" ON "PERSON" ((lower(last_name)));
CREATE INDEX "TM_LABEL_INDEX" ON "TEAM" ((lower(label)));

CREATE INDEX "CT_LABEL_FR_INDEX" ON "CITY" ((lower(label_fr)));
CREATE INDEX "CT_LABEL_INDEX" ON "CITY" ((lower(label)));



