-- Function: "~STATISTICS"()

-- DROP FUNCTION "~STATISTICS"();

CREATE OR REPLACE FUNCTION "~STATISTICS"()
  RETURNS refcursor AS
$BODY$
declare
	_c refcursor;
begin
	OPEN _c FOR EXECUTE
	'SELECT
		(SELECT COUNT(*) FROM "SPORT") AS COUNT_SPORT,
		(SELECT COUNT(*) FROM "EVENT") AS COUNT_EVENT,
		(SELECT COUNT(*) FROM "RESULT") AS COUNT_RESULT,
		(SELECT COUNT(*) FROM "PERSON") AS COUNT_PERSON';
	RETURN  _c;
end;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
